In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

from pandas.plotting import parallel_coordinates

#uses andrews curves
from pandas.plotting import andrews_curves

from sklearn import preprocessing 
from sklearn.decomposition import PCA

from sklearn import manifold


pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [14]:
# Look pretty...

# matplotlib.style.use('ggplot')
plt.style.use('ggplot')

In [15]:
X=pd.read_csv('train_values.csv',header=0,na_values='?')
y=pd.read_csv('train_labels.csv',header=0,na_values='?')
Z=pd.read_csv('test_values.csv',header=0,na_values='?')

In [16]:
Z1=Z.loc[:,'building_id']

In [18]:
X.describe()

        building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq           age          area        height  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other
count  10000.000000    10000.000000    10000.000000    10000.000000         10000.000000  10000.000000  10000.000000  10000.000000                  10000.000000                         10000.000000                    10000.00000                            10000.000000                         10000.000000                            10000.000000                 10000.0000               10000.000000                          10000.000000                      10000.000000              10000.000000    10000.000000       10000.000000                   10000.000000             10000.000000              10000.000000                    10000.00000               10000.00000                10000.000000                   10000.000000                  10000.000000                    10000.0000             10000.000000
mean    9987.160000        7.135600      296.930300     2678.617900             2.146700     25.393500     38.438100      4.653100                      0.089700                             0.762600                        0.02990                                0.019000                             0.068800                                0.072500                     0.2561                   0.087700                              0.040000                          0.013800                  0.014100        0.984600           0.108600                       0.067300                 0.029400                  0.006400                        0.00070                   0.00070                    0.000800                       0.000200                      0.000200                        0.0001                 0.005300
std     5800.800829        6.225567      279.390651     2520.663769             0.736365     64.482893     21.265883      1.792842                      0.285766                             0.425511                        0.17032                                0.136532                             0.253126                                0.259327                     0.4365                   0.282872                              0.195969                          0.116666                  0.117909        0.423297           0.311152                       0.250553                 0.168933                  0.079748                        0.02645                   0.02645                    0.028274                       0.014141                      0.014141                        0.0100                 0.072612
min        1.000000        0.000000        0.000000        0.000000             1.000000      0.000000      6.000000      1.000000                      0.000000                             0.000000                        0.00000                                0.000000                             0.000000                                0.000000                     0.0000                   0.000000                              0.000000                          0.000000                  0.000000        0.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
25%     4998.750000        2.000000       60.000000      606.750000             2.000000     10.000000     26.000000      4.000000                      0.000000                             1.000000                        0.00000                                0.000000                             0.000000                                0.000000                     0.0000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
50%     9963.500000        6.000000      219.000000     1937.500000             2.000000     15.000000     34.000000      5.000000                      0.000000                             1.000000                        0.00000                                0.000000                             0.000000                                0.000000                     0.0000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
75%    15044.750000       10.000000      466.000000     4158.000000             3.000000     30.000000     44.000000      5.000000                      0.000000                             1.000000                        0.00000                                0.000000                             0.000000                                0.000000                     1.0000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
max    19999.000000       30.000000     1411.000000    12151.000000             9.000000    995.000000    425.000000     30.000000                      1.000000                             1.000000                        1.00000                                1.000000                             1.000000                                1.000000                     1.0000                   1.000000                              1.000000                          1.000000                  1.000000        7.000000           1.000000                       1.000000                 1.000000                  1.000000                        1.00000                   1.00000                    1.000000                       1.000000                      1.000000                        1.0000                 1.000000

In [20]:
X[X.isnull().any(axis=1)]

Empty DataFrame
Columns: [building_id, geo_level_1_id, geo_level_2_id, geo_level_3_id, count_floors_pre_eq, age, area, height, land_surface_condition, foundation_type, roof_type, ground_floor_type, other_floor_type, position, plan_configuration, has_superstructure_adobe_mud, has_superstructure_mud_mortar_stone, has_superstructure_stone_flag, has_superstructure_cement_mortar_stone, has_superstructure_mud_mortar_brick, has_superstructure_cement_mortar_brick, has_superstructure_timber, has_superstructure_bamboo, has_superstructure_rc_non_engineered, has_superstructure_rc_engineered, has_superstructure_other, legal_ownership_status, count_families, has_secondary_use, has_secondary_use_agriculture, has_secondary_use_hotel, has_secondary_use_rental, has_secondary_use_institution, has_secondary_use_school, has_secondary_use_industry, has_secondary_use_health_post, has_secondary_use_gov_office, has_secondary_use_use_police, has_secondary_use_other]
Index: []

In [21]:
Xy=pd.merge(X,y,on='building_id')
Xy['count_families']=Xy.count_families.astype(np.int64)
Xy['has_secondary_use']=Xy.count_families.astype(np.int64)

In [22]:
X.loc[X.geo_level_1_id == 0, 'geo_level_1_id'] = np.nan
X.loc[X.geo_level_2_id == 0, 'geo_level_2_id'] = np.nan
X.loc[X.geo_level_3_id == 0, 'geo_level_3_id'] = np.nan

In [23]:
X.fillna(round(X.median()),inplace=True)

In [24]:
X.describe()

        building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq           age          area        height  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other
count  10000.000000    10000.000000    10000.000000    10000.000000         10000.000000  10000.000000  10000.000000  10000.000000                  10000.000000                         10000.000000                    10000.00000                            10000.000000                         10000.000000                            10000.000000                 10000.0000               10000.000000                          10000.000000                      10000.000000              10000.000000    10000.000000       10000.000000                   10000.000000             10000.000000              10000.000000                    10000.00000               10000.00000                10000.000000                   10000.000000                  10000.000000                    10000.0000             10000.000000
mean    9987.160000        7.677400      300.462800     2683.293100             2.146700     25.393500     38.438100      4.653100                      0.089700                             0.762600                        0.02990                                0.019000                             0.068800                                0.072500                     0.2561                   0.087700                              0.040000                          0.013800                  0.014100        0.984600           0.108600                       0.067300                 0.029400                  0.006400                        0.00070                   0.00070                    0.000800                       0.000200                      0.000200                        0.0001                 0.005300
std     5800.800829        5.829436      277.026219     2517.495486             0.736365     64.482893     21.265883      1.792842                      0.285766                             0.425511                        0.17032                                0.136532                             0.253126                                0.259327                     0.4365                   0.282872                              0.195969                          0.116666                  0.117909        0.423297           0.311152                       0.250553                 0.168933                  0.079748                        0.02645                   0.02645                    0.028274                       0.014141                      0.014141                        0.0100                 0.072612
min        1.000000        1.000000        1.000000        1.000000             1.000000      0.000000      6.000000      1.000000                      0.000000                             0.000000                        0.00000                                0.000000                             0.000000                                0.000000                     0.0000                   0.000000                              0.000000                          0.000000                  0.000000        0.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
25%     4998.750000        3.000000       67.750000      615.000000             2.000000     10.000000     26.000000      4.000000                      0.000000                             1.000000                        0.00000                                0.000000                             0.000000                                0.000000                     0.0000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
50%     9963.500000        6.000000      225.000000     1948.000000             2.000000     15.000000     34.000000      5.000000                      0.000000                             1.000000                        0.00000                                0.000000                             0.000000                                0.000000                     0.0000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
75%    15044.750000       10.000000      466.000000     4158.000000             3.000000     30.000000     44.000000      5.000000                      0.000000                             1.000000                        0.00000                                0.000000                             0.000000                                0.000000                     1.0000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                        0.00000                   0.00000                    0.000000                       0.000000                      0.000000                        0.0000                 0.000000
max    19999.000000       30.000000     1411.000000    12151.000000             9.000000    995.000000    425.000000     30.000000                      1.000000                             1.000000                        1.00000                                1.000000                             1.000000                                1.000000                     1.0000                   1.000000                              1.000000                          1.000000                  1.000000        7.000000           1.000000                       1.000000                 1.000000                  1.000000                        1.00000                   1.00000                    1.000000                       1.000000                      1.000000                        1.0000                 1.000000

In [26]:
Z['count_families']=Z.count_families.astype(np.int64)
Z['has_secondary_use']=Z.count_families.astype(np.int64)

In [27]:
X.set_index(['building_id'],inplace=True)
X.head(5)

             geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  age  area  height land_surface_condition foundation_type roof_type ground_floor_type other_floor_type position plan_configuration  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other legal_ownership_status  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other
building_id
765                     8.0           501.0          3237.0                    2   25    33       4                   d502            337f      7e76              b1b4             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1             1.0                0.0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
9470                    7.0           288.0          1819.0                    3   15    28       5                   d502            337f      7e76              b1b4             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1             0.0                0.0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
14461                  14.0            36.0           838.0                    1   20    37       2                   d502            337f      7e76              467b             441a     bfba               8e3f                             0                                    1                              0                                       0                                    1                                       0                          0                          0                                     0                                 0                         0                   c8e1             1.0                1.0                              0                        1                         0                              0                         0                           0                              0                             0                             0                        0
9317                    8.0            81.0           805.0                    2    5    18       3                   d502            337f      7e76              b1b4             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1             1.0                0.0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
15941                  23.0           380.0          4266.0                    3    0    39       6                   d502            337f      7e76              b1b4             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1             1.0                0.0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0

In [28]:
Z.set_index(['building_id'],inplace=True)
Z.head(5)

             geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  age  area  height land_surface_condition foundation_type roof_type ground_floor_type other_floor_type position plan_configuration  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other legal_ownership_status  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other
building_id
11456                     1              42             941                    2    0    24       4                   d502            6c3e  7.00E+76              b1b4             f962     3356               a779                             0                                    0                              0                                       0                                    0                                       1                          0                          0                                     0                                 0                         0                   c8e1               1                  1                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
16528                     4             227            1857                    2   15    20       3                   d502            337f  7.00E+76              b1b4             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1               1                  1                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
3253                     10             361            4646                    2   10    29       3                   d502            337f  7.00E+76              b440             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          1                          1                                     0                                 0                         0                   c8e1               1                  1                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
18614                     0             275            3537                    2   10    37       6                   d502            337f  7.00E+76              b1b4             f962     bfba               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1               0                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0
1544                      5             370            2025                    3   25    35       5                   d502            337f  7.00E+76              b1b4             f962     3356               a779                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                   c8e1               1                  1                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0

In [29]:
y.set_index('building_id',inplace=True)

In [31]:
X=pd.get_dummies(X)
Z=pd.get_dummies(Z)

In [32]:
# List of features for later use
feature_list = list(X.columns)

In [35]:
#Normalizer=preprocessing.Normalizer()
#MinMaxScaler=preprocessing.MinMaxScaler()
StandardScaler=preprocessing.StandardScaler()
#MaxAbsScaler=preprocessing.MaxAbsScaler()
#RobustScaler=preprocessing.RobustScaler()
#X=Normalizer.fit_transform(X)
#Z=Normalizer.fit_transform(Z)
#Xy=Normalizer.fit_transform(Xy)

#X=MinMaxScaler.fit_transform(X)
#Z=MinMaxScaler.fit_transform(Z)
#Xy=MinMaxScaler.fit_transform(Xy)

X=StandardScaler.fit_transform(X)
Z=StandardScaler.fit_transform(Z)
#Xy=StandardScaler.fit_transform(Xy)

#X=MaxAbsScaler.fit_transform(X)
#Z=MaxAbsScaler.fit_transform(Z)
#Xy=MaxAbsScaler.fit_transform(Xy)

#X=RobustScaler.fit_transform(X)
#Z=RobustScaler.fit_transform(Z)
#Xy=RobustScaler.fit_transform(Xy)

In [36]:
X.shape

(10000, 67)

In [37]:
Z.shape

(10000, 67)

In [38]:
y.shape

(10000, 1)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.33, random_state=7)

In [41]:
model = manifold.Isomap(n_neighbors=5, n_components=2)
X_t_train=model.fit_transform(X_train)
X_t_test=model.transform(X_test)

In [57]:
Z.shape

(10000, 67)

In [60]:
y_t_train=y_train.iloc[:,0]
y_t_test=y_test.iloc[:,0]

In [61]:
##OneVsOneClassifier with RandomForest
##Run Cross_Val_Score on the model

from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier


from sklearn.utils import shuffle

#clf = RandomForestClassifier(n_estimators=150, random_state=1,oob_score=True,bootstrap=True)
#clf=RandomForestClassifier(n_estimators=150, random_state=1, bootstrap=True, criterion= 'entropy', max_depth= None)
clf = OneVsOneClassifier(RandomForestClassifier(n_estimators=150, random_state=1,oob_score=True,criterion='gini'))
cross_val_score(clf, X_train, y_t_train, cv=10)

array([0.62891207, 0.64828614, 0.6438152 , 0.63283582, 0.63283582,
       0.65970149, 0.67014925, 0.66218236, 0.66816143, 0.67414051])

In [63]:
X_train.shape

(6700, 67)

In [64]:
clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

OneVsOneClassifier(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False),
          n_jobs=1)

In [67]:
# Make predictions on test data
predictions = clf.predict(X_test)
# Performance metrics
errors = abs(predictions - y_t_test)
print('Average absolute error:', round(np.mean(errors), 2), 'degrees.')
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_t_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Average absolute error: 0.33 degrees.
Accuracy: 83.43 %.

In [68]:
clf.score(X_test,y_test)

0.6742424242424242

In [69]:
from sklearn.metrics import f1_score
f1_score(y_test, predictions, average='micro')

0.6742424242424242

In [70]:
#use the test_date to predict
clfPred=clf.predict(Z)

In [71]:
#write to csv
prediction = pd.DataFrame(clfPred, index=Z1, columns=['damage_grade']).to_csv('prediction_RForest.csv')